def generate_vehicle_qr(vehicle):
    """Generate a QR code image with structured offline vehicle data."""
    import qrcode
    from io import BytesIO

    def fmt_date(d):
        return d.strftime("%d-%m-%Y") if d else "Not Set"

    def get_current_expiry(doc_type):
        """Get current expiry for a document type (multi-expiry or legacy)."""
        current = vehicle.get_current_expiry(doc_type)
        if current:
            return current.expiry_date
        # Fallback to legacy
        field = vehicle.DOCUMENT_FIELDS.get(doc_type)
        if field:
            return getattr(vehicle, field)
        return None

    report_id = f"VC-{vehicle.created_at.strftime('%Y%m%d')}-{vehicle.id:04d}" if vehicle.created_at else f"VC-{vehicle.id:04d}"

    qr_text = (
        "VCMS - VEHICLE COMPLIANCE\n"
        f"{'=' * 32}\n"
        "\n"
        f"Vehicle No  : {vehicle.vehicle_number}\n"
        f"Vehicle ID  : {vehicle.id}\n"
        f"Report ID   : {report_id}\n"
        "\n"
        f"Owner       : {vehicle.owner_name}\n"
        f"Mobile      : {vehicle.mobile_number or 'N/A'}\n"
        "\n"
        f"Type        : {vehicle.vehicle_type or 'N/A'}\n"
        f"District    : {vehicle.district or 'N/A'}\n"
        f"Registration: {fmt_date(vehicle.registration_date)}\n"
        "\n"
        f"Chassis     : {vehicle.chassis_number}\n"
        f"Engine      : {vehicle.engine_number or 'N/A'}\n"
        "\n"
        f"{'-' * 32}\n"
        "DOCUMENT STATUS\n"
        f"{'-' * 32}\n"
        "\n"
    )

    # Document expiries - show current for each type
    for doc_type in vehicle.DOCUMENT_TYPES:
        expiry = get_current_expiry(doc_type)
        label = doc_type.ljust(12)
        qr_text += f"{label}: {fmt_date(expiry)}\n"

    qr_text += "\n"
    qr_text += f"Tax Mode    : {vehicle.tax_mode or 'N/A'}\n"
    qr_text += f"Tax Amount  : {'₹%.2f' % vehicle.tax_amount if vehicle.tax_amount else 'N/A'}\n"
    qr_text += "\n"
    qr_text += f"Insurance Co: {vehicle.insurance_company or 'N/A'}\n"
    qr_text += f"Policy No   : {vehicle.policy_number or 'N/A'}\n"
    qr_text += f"Pollution   : {vehicle.pollution_certificate_number or 'N/A'}\n"
    "\n"

    if vehicle.remarks:
        qr_text += f"Remarks     : {vehicle.remarks}\n"
        qr_text += "\n"
    qr_text += "Generated by VCMS\n"

    qr = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=6,
        border=2,
    )
    qr.add_data(qr_text)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    buffer = BytesIO()
    img.save(buffer, format="PNG")
    buffer.seek(0)
    return buffer
