def generate_vehicle_qr(vehicle):
    """Generate a QR code image with structured offline vehicle data."""
    import qrcode
    from io import BytesIO

    def fmt_date(d):
        return d.strftime("%d-%m-%Y") if d else "Not Set"

    report_id = f"VC-{vehicle.created_at.strftime('%Y%m%d')}-{vehicle.id:04d}" if vehicle.created_at else f"VC-{vehicle.id:04d}"

    qr_text = (
        "VCMS - VEHICLE COMPLIANCE\n"
        f"{'=' * 32}\n"
        "\n"
        f"Vehicle No  : {vehicle.vehicle_number}\n"
        f"Vehicle ID  : {vehicle.id}\n"
        f"Report ID   : {report_id}\n"
        "\n"
        f"Owner       : {vehicle.owner_name}\n"
        f"Mobile      : {vehicle.mobile_number or 'N/A'}\n"
        "\n"
        f"Type        : {vehicle.vehicle_type or 'N/A'}\n"
        f"District    : {vehicle.district or 'N/A'}\n"
        f"Registration: {fmt_date(vehicle.registration_date)}\n"
        "\n"
        f"Chassis     : {vehicle.chassis_number}\n"
        f"Engine      : {vehicle.engine_number or 'N/A'}\n"
        "\n"
        f"{'-' * 32}\n"
        "DOCUMENT STATUS\n"
        f"{'-' * 32}\n"
        "\n"
        f"PUC         : {fmt_date(vehicle.puc_expiry)}\n"
        f"Fitness     : {fmt_date(vehicle.fitness_expiry)}\n"
        f"Permit      : {fmt_date(vehicle.permit_expiry)}\n"
        f"Tax         : {fmt_date(vehicle.tax_expiry)}\n"
        f"Tax Mode    : {vehicle.tax_mode or 'N/A'}\n"
        f"Tax Amount  : {'₹%.2f' % vehicle.tax_amount if vehicle.tax_amount else 'N/A'}\n"
        f"Insurance   : {fmt_date(vehicle.insurance_expiry)}\n"
        f"Nat Permit  : {fmt_date(vehicle.national_permit_expiry)}\n"
        f"State Permit: {fmt_date(vehicle.state_permit_expiry)}\n"
        "\n"
        f"Insurance Co: {vehicle.insurance_company or 'N/A'}\n"
        f"Policy No   : {vehicle.policy_number or 'N/A'}\n"
        f"Pollution   : {vehicle.pollution_certificate_number or 'N/A'}\n"
        "\n"
    )
    if vehicle.remarks:
        qr_text += f"Remarks     : {vehicle.remarks}\n"
        qr_text += "\n"
    qr_text += "Generated by VCMS\n"

    qr = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=6,
        border=2,
    )
    qr.add_data(qr_text)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    buffer = BytesIO()
    img.save(buffer, format="PNG")
    buffer.seek(0)
    return buffer
