"""Shared application constants."""

EXPORT_COLUMNS = [
    ("vehicle_number", "Vehicle Number"),
    ("chassis_number", "Chassis Number"),
    ("engine_number", "Engine Number"),
    ("owner_name", "Owner Name"),
    ("mobile_number", "Mobile Number"),
    ("owner_email", "Owner Email"),
    ("vehicle_type", "Vehicle Type"),
    ("district", "District"),
    ("registration_date", "Registration Date"),
    ("puc_expiry", "PUC Expiry"),
    ("fitness_expiry", "Fitness Expiry"),
    ("permit_expiry", "Permit Expiry"),
    ("permit_from", "Permit From"),
    ("permit_auth_no", "Permit Auth No."),
    ("permit_address", "Address"),
    ("tax_expiry", "Tax Expiry"),
    ("tax_from", "Tax From"),
    ("tax_mode", "Tax Mode"),
    ("tax_amount", "Tax Amount"),
    ("insurance_expiry", "Insurance Expiry"),
    ("national_permit_expiry", "National Permit Expiry"),
    ("state_permit_expiry", "State Permit Expiry"),
    ("insurance_company", "Insurance Company"),
    ("policy_number", "Policy Number"),
    ("pollution_certificate_number", "Pollution Cert. No."),
    ("remarks", "Remarks"),
    ("created_at", "Created At"),
    ("updated_at", "Updated At"),
]
